spring.application.name=langgraph-agent-backend
server.port=8080
spring.jackson.default-property-inclusion=non_null

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.force-response=true
